### ISSUE TITLE
Doesn't work artisan command

### ISSUE THREAD

**Issue by MrFallen** [laravel-101/multi-domain-laravel-app#5]
```
php artisan route:cache
php artisan optimize
```
![image](https://user-images.githubusercontent.com/5339386/75842005-eefdea00-5e1a-11ea-8bff-1ffab9ad425a.png)

**Comment by maxkostinevich** [comment]
The command `php artisan route:cache` does not work with Closure functions as stated in [documentation](https://laravel.com/docs/5.8/controllers#route-caching).
