### ISSUE TITLE
How to setup this example?

### ISSUE THREAD

**Issue by MrFallen** [laravel-101/multi-domain-laravel-app#6]
Localhost with Open Server:
![image](https://user-images.githubusercontent.com/5339386/75847591-5fad0280-5e2b-11ea-9d7c-6fdd6dd958b2.png)
VDS with VestaCP:
![image](https://user-images.githubusercontent.com/5339386/75847620-705d7880-5e2b-11ea-9543-1e723af3658d.png)
What am I doing wrong? :(

**Comment by maxkostinevich** [comment]
Obviously, you can't use subdomains if you access a webserver by IP Address, you need to use Ngrok or something like this.

Have no idea how to make it work with VestaCP.

**Comment by MrFallen** [comment]
@maxkostinevich maybe you have detailed installation instructions?
